name: ProjectArenas
author: Simplicitee
api-version: 1.15
version: 1.0.5
main: me.simplicitee.project.arenas.ProjectArenas
depend: [ProjectKorra]
commands:
  arena:
    aliases: [pas, arenas, projectarenas, projectarena, parena]
    usage: /<command>
permissions:
  projectarenas.admin:
    default: op
    children:
      projectarenas.editor: true
      projectarenas.reload: true